# Generated by Django 4.0.4 on 2023-05-03 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия игрок')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram id')),
                ('score', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст вопроса', max_length=1000, verbose_name='Текст вопроса')),
                ('date', models.DateTimeField(help_text='Дата отправки вопроса', verbose_name='Дата отправки вопроса')),
                ('comment', models.CharField(help_text='Комментарий', max_length=500, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ForeignKey(help_text='Вопрос', on_delete=django.db.models.deletion.CASCADE, to='quester.question')),
            ],
        ),
    ]
