# Generated by Django 4.0.4 on 2023-05-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default='', max_length=100, verbose_name='Ответ на вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(default=0, verbose_name='Количество правильных ответов'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_users',
            field=models.ManyToManyField(blank=True, to='quester.player'),
        ),
    ]
