# Generated by Django 4.0.4 on 2024-06-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quester', '0004_question_task_id_alter_question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status_news',
            field=models.BooleanField(default=True, verbose_name='News subscribe status'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Question subscribe status'),
        ),
    ]
