# Generated by Django 4.0.4 on 2024-06-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quester', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prizes_count',
            field=models.IntegerField(default=10, verbose_name='Number of prizes'),
        ),
    ]
